apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-kong
data:
  KONG_DATABASE: 'off'
  KONG_PROXY_ACCESS_LOG: '/dev/stdout'
  KONG_ADMIN_ACCESS_LOG: '/dev/stdout'
  KONG_PROXY_ERROR_LOG: '/dev/stderr'
  KONG_ADMIN_ERROR_LOG: '/dev/stderr'
  KONG_DECLARATIVE_CONFIG: '/etc/kong/kong.yml'
  KONG_ADMIN_LISTEN: '127.0.0.1:8001, 127.0.0.1:8444 ssl'