apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-declarative
data:
  kong.yml: |
    _format_version: "3.0"

    _transform: true

    services:
    - name: argo-cd-service
      url: http://argocd-server:80/
      routes:
      - name: argo-cd-route
        https_redirect_status_code: 301
        path_handling: v1
        protocols:
        - https
        paths:
        - /

    - name: admin-api-service
      url: http://127.0.0.1:8001/
      routes:
      - name: admin-api-route
      https_redirect_status_code: 301
      path_handling: v1
      plugins:
        - name: key-auth
        protocols:
        - http
        - https
        paths:
        - /admin-api

    consumers:
      - username: acme-consumer
        keyauth_credentials:
        - key: DQgeVCuSZvBWzA